version: 2
updates:
  # Flutter / Dart dependencies (pubspec.yaml)
  - package-ecosystem: "pub"
    directory: "/" # location of pubspec.yaml
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(pub)"
      include: "scope"

  # GitHub Actions dependencies (workflow versions)
  - package-ecosystem: "github-actions"
    directory: "/" # location of workflow files (.github/workflows)
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
