name: Deploy Flutter Web to Firebase Hosting

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable # Defaults to the latest stable version
      - run: flutter --version

      # Flutter dependencies setup
      - name: Install Flutter dependencies
        run: flutter pub get

      # Build the Flutter web project
      - name: Build Flutter Web
        run: flutter build web --release

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: restaurantzz
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
